# Generated by Django 5.2.8 on 2025-11-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elementary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=255)),
                ('schooladdress', models.CharField(max_length=255)),
                ('honors', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=255)),
                ('schooladdress', models.CharField(max_length=255)),
                ('honors', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SeniorHigh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=255)),
                ('schooladdress', models.CharField(max_length=255)),
                ('honors', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
